{{- $val := .Values -}}
{{- if .Values.autoscaling }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: znuny
    service: {{ .Release.Name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}
  minReplicas: {{ $val.autoscaling.minReplicas }}
  maxReplicas: {{ $val.autoscaling.maxReplicas }}
  metrics:
    {{- if $val.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ $val.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if $val.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ $val.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
