name: Znuny_Unstable_Container_Images

on:
  push:
    branches:
      - '*.*.*'

env:
  REGISTRY: ghcr.io
  ORGANIZATION: fr-bez-aosc
  IMAGE_NAME: znuny

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into ${{ env.REGISTRY }} registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract previous Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.ORGANIZATION }}/${{ env.IMAGE_NAME }}

      - name: Extract tag name
        id: extract-tag
        run: echo "GIT_BRANCH=${GITHUB_REF/refs\/heads\//}" >> $GITHUB_ENV

      - name: Build and push Docker image
        id: build-and-push-tag
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./znuny/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.ORGANIZATION }}/${{ env.IMAGE_NAME }}:beta-${{ env.GIT_BRANCH }}
          labels: |
            ${{ steps.meta.outputs.labels }}
            ${{ github.ref }}

